.TH "README.txt" 3 "Thu Nov 5 2020" "Version 0.9" "Lab one: HelloThreads - The Toolchai" \" -*- nroff -*-
.ad l
.nh
.SH NAME
README.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "This work is licensed under the Creative Commons Attribution NonCommercial NoDerivatives International License To view a copy of this \fBlicense\fP"
.br
.ti -1c
.RI "This work is licensed under the Creative Commons Attribution NonCommercial NoDerivatives International License To view a copy of this visit \fBhttp\fP"
.br
.ti -1c
.RI "This work is licensed under the Creative Commons Attribution NonCommercial NoDerivatives International License To view a copy of this visit Year Software Development student at IT \fBCarlow\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "This work is licensed under the Creative Commons Attribution NonCommercial NoDerivatives International License To view a copy of this visit Year Software Development student at IT Carlow"

.SS "This work is licensed under the Creative Commons Attribution NonCommercial NoDerivatives International License To view a copy of this visit http"

.SS "This work is licensed under the Creative Commons Attribution NonCommercial NoDerivatives International License To view a copy of this license"

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab one: HelloThreads - The Toolchai from the source code\&.
