.TH "test.cpp" 3 "Thu Nov 5 2020" "Version 0.9" "Lab one: HelloThreads - The Toolchai" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab one: HelloThreads - The Toolchai from the source code\&.
