.TH "Semaphore.h" 3 "Wed Nov 4 2020" "Version 0.9" "Lab 2 Signalling with Semaphores" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Semaphore.h
.SH SYNOPSIS
.br
.PP
\fC#include <mutex>\fP
.br
\fC#include <condition_variable>\fP
.br
\fC#include <chrono>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSemaphore\fP"
.br
.RI "A \fBSemaphore\fP Implementation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Lab 2 Signalling with Semaphores from the source code\&.
