.TH "Signal" 3 "Thu Nov 5 2020" "Version 0.9" "Lab Two: Signalling with Semaphores" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Signal \- An Implementation of Threads Using Semaphores\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
An Implementation of Threads Using Semaphores\&. 

Author: Peter Lucan Student Number: C00228946 Date: 03/11/2020 Name :Lab Two - Signalling with Semaphores Decription: Uses a \fBSemaphore\fP which ensures that one thread finished it's actions beore another thread can begin\&.
.PP
Uses C++11 features such as mutex and condition variables to implement Semaphores in thread functions
.PP
Uses C++11 features such as mutex and condition variables to implement Semaphores in thread functions 

.SH "Author"
.PP 
Generated automatically by Doxygen for Lab Two: Signalling with Semaphores from the source code\&.
